# -*- coding: utf-8 -*-
"""Training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1siaiQWOdv9W4ECWEmZ1VIIIqP8PMexbT

# Welcome to Colab!
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

print("Libraries imported successfully.")

df = pd.read_csv('/content/Contacts.Gamma.csv')
print("Dataset loaded successfully.")

print(df.head())
print(df.info())

df['is_odd_contact'] = df['Contact Number'].apply(lambda x: 1 if x % 2 != 0 else 0)

# Extract the numeric part from the 'Name' column to use as a feature
# Assuming the format is 'YYYYDD######' where ###### is a unique identifier
df['Name_numeric_id'] = df['Name'].str.extract(r'(\d+)$').astype(int)

# Define features (X) and target (y)
X = df[['Name_numeric_id']]
y = df['is_odd_contact']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Data prepared for Logistic Regression:")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Logistic Regression model applied and predictions made.")

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("\nClassification Report:\n", report)
print("\nConfusion Matrix:\n", cm)

display_cm = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=model.classes_)
display_cm.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()

print(f"Accuracy: {accuracy:.2f}")